/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RacFormatAnyOf the model 'RacFormatAnyOf'
type RacFormatAnyOf string

// List of RacFormat_anyOf
const (
	_5_GS RacFormatAnyOf = "5GS"
	EPS RacFormatAnyOf = "EPS"
)

func (v *RacFormatAnyOf) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RacFormatAnyOf(value)
	for _, existing := range []RacFormatAnyOf{ "5GS", "EPS",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RacFormatAnyOf", value)
}

// Ptr returns reference to RacFormat_anyOf value
func (v RacFormatAnyOf) Ptr() *RacFormatAnyOf {
	return &v
}

type NullableRacFormatAnyOf struct {
	value *RacFormatAnyOf
	isSet bool
}

func (v NullableRacFormatAnyOf) Get() *RacFormatAnyOf {
	return v.value
}

func (v *NullableRacFormatAnyOf) Set(val *RacFormatAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRacFormatAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRacFormatAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRacFormatAnyOf(val *RacFormatAnyOf) *NullableRacFormatAnyOf {
	return &NullableRacFormatAnyOf{value: val, isSet: true}
}

func (v NullableRacFormatAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRacFormatAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

