/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"os"
)



// ADictionaryEntryDocumentApiRouter defines the required methods for binding the api requests to a responses for the ADictionaryEntryDocumentApi
// The ADictionaryEntryDocumentApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ADictionaryEntryDocumentApiServicer to perform the required actions, then write the service results to the http response.
type ADictionaryEntryDocumentApiRouter interface { 
	CreateDictionaryEntry(http.ResponseWriter, *http.Request)
}
// DicEntryIdDocumentApiRouter defines the required methods for binding the api requests to a responses for the DicEntryIdDocumentApi
// The DicEntryIdDocumentApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DicEntryIdDocumentApiServicer to perform the required actions, then write the service results to the http response.
type DicEntryIdDocumentApiRouter interface { 
	GetDicEntry(http.ResponseWriter, *http.Request)
}
// DictionaryEntryStoreApiRouter defines the required methods for binding the api requests to a responses for the DictionaryEntryStoreApi
// The DictionaryEntryStoreApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DictionaryEntryStoreApiServicer to perform the required actions, then write the service results to the http response.
type DictionaryEntryStoreApiRouter interface { 
	RetrieveDictionaryEntry(http.ResponseWriter, *http.Request)
}
// IndividualSubscriptionDocumentApiRouter defines the required methods for binding the api requests to a responses for the IndividualSubscriptionDocumentApi
// The IndividualSubscriptionDocumentApiRouter implementation should parse necessary information from the http request, 
// pass the data to a IndividualSubscriptionDocumentApiServicer to perform the required actions, then write the service results to the http response.
type IndividualSubscriptionDocumentApiRouter interface { 
	DeleteIndividualSubcription(http.ResponseWriter, *http.Request)
}
// SubscriptionsCollectionApiRouter defines the required methods for binding the api requests to a responses for the SubscriptionsCollectionApi
// The SubscriptionsCollectionApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SubscriptionsCollectionApiServicer to perform the required actions, then write the service results to the http response.
type SubscriptionsCollectionApiRouter interface { 
	CreateIndividualSubcription(http.ResponseWriter, *http.Request)
}


// ADictionaryEntryDocumentApiServicer defines the api actions for the ADictionaryEntryDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type ADictionaryEntryDocumentApiServicer interface { 
	CreateDictionaryEntry(context.Context, DicEntryCreateData, *os.File, *os.File) (ImplResponse, error)
}


// DicEntryIdDocumentApiServicer defines the api actions for the DicEntryIdDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DicEntryIdDocumentApiServicer interface { 
	GetDicEntry(context.Context, int32, RacFormat) (ImplResponse, error)
}


// DictionaryEntryStoreApiServicer defines the api actions for the DictionaryEntryStoreApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DictionaryEntryStoreApiServicer interface { 
	RetrieveDictionaryEntry(context.Context, UeRadioCapaId, RacFormat) (ImplResponse, error)
}


// IndividualSubscriptionDocumentApiServicer defines the api actions for the IndividualSubscriptionDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type IndividualSubscriptionDocumentApiServicer interface { 
	DeleteIndividualSubcription(context.Context, string) (ImplResponse, error)
}


// SubscriptionsCollectionApiServicer defines the api actions for the SubscriptionsCollectionApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type SubscriptionsCollectionApiServicer interface { 
	CreateIndividualSubcription(context.Context, CreateSubscription) (ImplResponse, error)
}
