/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DicEntryCreateData struct for DicEntryCreateData
type DicEntryCreateData struct {
	TypeAllocationCode string `json:"typeAllocationCode"`
	UeRadioCapability5GS *RefToBinaryData `json:"ueRadioCapability5GS,omitempty"`
	UeRadioCapabilityEPS *RefToBinaryData `json:"ueRadioCapabilityEPS,omitempty"`
}

// NewDicEntryCreateData instantiates a new DicEntryCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDicEntryCreateData(typeAllocationCode string, ) *DicEntryCreateData {
	this := DicEntryCreateData{}
	this.TypeAllocationCode = typeAllocationCode
	return &this
}

// NewDicEntryCreateDataWithDefaults instantiates a new DicEntryCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDicEntryCreateDataWithDefaults() *DicEntryCreateData {
	this := DicEntryCreateData{}
	return &this
}

// GetTypeAllocationCode returns the TypeAllocationCode field value
func (o *DicEntryCreateData) GetTypeAllocationCode() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.TypeAllocationCode
}

// GetTypeAllocationCodeOk returns a tuple with the TypeAllocationCode field value
// and a boolean to check if the value has been set.
func (o *DicEntryCreateData) GetTypeAllocationCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TypeAllocationCode, true
}

// SetTypeAllocationCode sets field value
func (o *DicEntryCreateData) SetTypeAllocationCode(v string) {
	o.TypeAllocationCode = v
}

// GetUeRadioCapability5GS returns the UeRadioCapability5GS field value if set, zero value otherwise.
func (o *DicEntryCreateData) GetUeRadioCapability5GS() RefToBinaryData {
	if o == nil || o.UeRadioCapability5GS == nil {
		var ret RefToBinaryData
		return ret
	}
	return *o.UeRadioCapability5GS
}

// GetUeRadioCapability5GSOk returns a tuple with the UeRadioCapability5GS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DicEntryCreateData) GetUeRadioCapability5GSOk() (*RefToBinaryData, bool) {
	if o == nil || o.UeRadioCapability5GS == nil {
		return nil, false
	}
	return o.UeRadioCapability5GS, true
}

// HasUeRadioCapability5GS returns a boolean if a field has been set.
func (o *DicEntryCreateData) HasUeRadioCapability5GS() bool {
	if o != nil && o.UeRadioCapability5GS != nil {
		return true
	}

	return false
}

// SetUeRadioCapability5GS gets a reference to the given RefToBinaryData and assigns it to the UeRadioCapability5GS field.
func (o *DicEntryCreateData) SetUeRadioCapability5GS(v RefToBinaryData) {
	o.UeRadioCapability5GS = &v
}

// GetUeRadioCapabilityEPS returns the UeRadioCapabilityEPS field value if set, zero value otherwise.
func (o *DicEntryCreateData) GetUeRadioCapabilityEPS() RefToBinaryData {
	if o == nil || o.UeRadioCapabilityEPS == nil {
		var ret RefToBinaryData
		return ret
	}
	return *o.UeRadioCapabilityEPS
}

// GetUeRadioCapabilityEPSOk returns a tuple with the UeRadioCapabilityEPS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DicEntryCreateData) GetUeRadioCapabilityEPSOk() (*RefToBinaryData, bool) {
	if o == nil || o.UeRadioCapabilityEPS == nil {
		return nil, false
	}
	return o.UeRadioCapabilityEPS, true
}

// HasUeRadioCapabilityEPS returns a boolean if a field has been set.
func (o *DicEntryCreateData) HasUeRadioCapabilityEPS() bool {
	if o != nil && o.UeRadioCapabilityEPS != nil {
		return true
	}

	return false
}

// SetUeRadioCapabilityEPS gets a reference to the given RefToBinaryData and assigns it to the UeRadioCapabilityEPS field.
func (o *DicEntryCreateData) SetUeRadioCapabilityEPS(v RefToBinaryData) {
	o.UeRadioCapabilityEPS = &v
}

func (o DicEntryCreateData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["typeAllocationCode"] = o.TypeAllocationCode
	}
	if o.UeRadioCapability5GS != nil {
		toSerialize["ueRadioCapability5GS"] = o.UeRadioCapability5GS
	}
	if o.UeRadioCapabilityEPS != nil {
		toSerialize["ueRadioCapabilityEPS"] = o.UeRadioCapabilityEPS
	}
	return json.Marshal(toSerialize)
}

type NullableDicEntryCreateData struct {
	value *DicEntryCreateData
	isSet bool
}

func (v NullableDicEntryCreateData) Get() *DicEntryCreateData {
	return v.value
}

func (v *NullableDicEntryCreateData) Set(val *DicEntryCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableDicEntryCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableDicEntryCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDicEntryCreateData(val *DicEntryCreateData) *NullableDicEntryCreateData {
	return &NullableDicEntryCreateData{value: val, isSet: true}
}

func (v NullableDicEntryCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDicEntryCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


