/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// ADictionaryEntryDocumentApiService is a service that implents the logic for the ADictionaryEntryDocumentApiServicer
// This service should implement the business logic for every endpoint for the ADictionaryEntryDocumentApi API. 
// Include any external packages or services that will be required by this service.
type ADictionaryEntryDocumentApiService struct {
}

// NewADictionaryEntryDocumentApiService creates a default api service
func NewADictionaryEntryDocumentApiService() ADictionaryEntryDocumentApiServicer {
	return &ADictionaryEntryDocumentApiService{}
}

// CreateDictionaryEntry - Create a dictionary entry in the UCMF
func (s *ADictionaryEntryDocumentApiService) CreateDictionaryEntry(ctx context.Context, jsonData DicEntryCreateData, binaryDataUeRadioCapability5GS *os.File, binaryDataUeRadioCapabilityEPS *os.File) (ImplResponse, error) {
	// TODO - update CreateDictionaryEntry with the required logic for this service method.
	// Add api_a_dictionary_entry_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, DicEntryCreatedData{}) or use other options such as http.Ok ...
	//return Response(201, DicEntryCreatedData{}), nil

	//TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(400, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(403, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(411, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(411, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(413, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(413, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(415, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(429, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(500, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(501, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(501, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(503, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateDictionaryEntry method not implemented")
}

