/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EventTypeAnyOf string

// List of EventTypeAnyOf
const (
	CREATION_OF_DICTIONARY_ENTRY EventTypeAnyOf = "CREATION_OF_DICTIONARY_ENTRY"
	DELETION_OF_PLMN_ASSIGNED_IDS EventTypeAnyOf = "DELETION_OF_PLMN_ASSIGNED_IDS"
	NEW_VERSION_ID_OF_PLMN_ASSIGNED_IDS EventTypeAnyOf = "NEW_VERSION_ID_OF_PLMN_ASSIGNED_IDs"
)
