/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"os"
)

type InlineObject struct {

	JsonData DicEntryCreateData `json:"jsonData,omitempty" bson:"jsonData"`

	BinaryDataUeRadioCapability5GS *os.File `json:"binaryDataUeRadioCapability5GS,omitempty" bson:"binaryDataUeRadioCapability5GS"`

	BinaryDataUeRadioCapabilityEPS *os.File `json:"binaryDataUeRadioCapabilityEPS,omitempty" bson:"binaryDataUeRadioCapabilityEPS"`
}
